{
 "title": "Indexer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "BTC Sync",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "btc_scanned_height/btc_current_height",
     "legendFormat": "Sync Percent"
    }
   ]
  },
  {
   "title": "Desync",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "btc_current_height - btc_scanned_height"
    }
   ]
  },
  {
   "title": "Scanned height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "btc_scanned_height", "legendFormat": "BTC Blocks" },
    { "expr": "ergo_scanned_height", "legendFormat": "ERGO Blocks" }
   ]
  },
  {
   "title": "Node height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "btc_current_height", "legendFormat": "BTC" },
    { "expr": "ergo_current_height", "legendFormat": "ERGO" }
   ]
  },
  {
   "title": "Available storage space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "available_space", "legendFormat": "Storage space" }
   ]
  },
  {
   "title": "Scan rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(btc_scanned_height[1m])", "legendFormat": "BTC scan rate per min" },
    { "expr": "rate(ergo_scanned_height[1m])", "legendFormat": "ERGO scan rate per min" }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "active_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Served filters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "filters_served", "legendFormat": "Amount of served filters" }
   ]
  },
  {
   "title": "Live memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Live data" }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "fds" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "File descriptors opened" }
   ]
  },
  {
   "title": "Desync",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "btc_current_height - btc_scanned_height",
     "legendFormat": "Desycned blocks"
    }
   ]
  }
 ]
}